[#32] 깃허브 OAuth 로그인 기능을 구현한다.
codesquad-member-2020/issue-tracker-04 pull request #33
Opened 2020-06-14 07:59 UTC by guswns1659

## 진행사항
- 시큐리티 이용해서 로그인 기능 구현하려고 했는데 잘 안되서 기존 방식대로 구현 시도했어요!
- 현재 로그인 성공하면 사용자의 아이디를 깃허브에 요청해서 받아오는 기능까지 구현했습니다.
## 논의사항 
- 로그인 성공 시 클라이언트 개발자에게 인증 토큰을 어떻게 넘길 지 이야기 나눠봐요. 
  - 전에는 웹 개발자여서 쿠키로 넘기긴 했는데, iOS는 의문이네요.

2020-06-14 08:19 UTC, jypthemiracle commented
주말에도 열심히 이군요. :)

2020-06-14 08:21 UTC, jypthemiracle commented
저는 지난 번에 iOS는 쿠키로 해서 넘겼습니다.
다만 이번에도 리다이렉션 시 uri scheme를 요구할 가능성이 높습니다. 읽어보시구요. https://blog.branch.io/ko/유니버설-링크-uri-스킴-앱-링크-및-딥-링크-무슨-차이가/

2020-06-14 14:20 UTC, sigridjineth requested changes
몇 가지 커멘트 남겨드렸구요.
일단 스프링 시큐리티 적용을 해보는 방향으로 해봅시다. 어떠한 오류가 있으셨는지 알려주시면 내일 같이 고민해볼 수 있어 보이네요.

2020-06-14 14:20 UTC, realsigridjin commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea 커밋되었는데 gitignore 확인 부탁드립니다.

2020-06-14 14:20 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
> +public class RestTemplateConfig {
RestTemplate을 별도의 Config로 설정할 수 있네요?! 처음 봤습니다.

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
> +public class RestTemplateConfig {
어떻게 되는 건지 내일 알려줘요.

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +	public ResponseEntity<Void> login(String code, HttpServletResponse response) {
Void???????????????????

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +		if (userId.contains("\"")) {
이게 뭐죠?

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +		String[] splitTokens2 = splitTokens[0].split("=");
변수명이 아쉽네요

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +		return splitTokens2[1];
매직넘버 사용은 지양해주세요.

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/utils/GithubProperties.java
> +@ConfigurationProperties("github")
오 이 어노테이션은 처음 봐요.

2020-06-14 14:20 UTC, jypthemiracle commented on BE/src/main/resources/application-oauth.yml
> +  clientId : bdd909bfff2137535182
여기서 실패한거죠?

2020-06-15 00:37 UTC, guswns1659 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
넵

2020-06-15 00:38 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
> +public class RestTemplateConfig {
원리는 정확히 모르지만 ㅋㅋ 네네!

2020-06-15 00:40 UTC, guswns1659 commented on BE/src/main/resources/application-oauth.yml
> +  clientId : bdd909bfff2137535182
네네!

2020-06-15 02:57 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +	public ResponseEntity<Void> login(String code, HttpServletResponse response) {
@guswns1659 Void 객체를 사용하는 것이 옳을까요? 반환값이 없다는 뜻으로 읽히는데요.

2020-06-15 02:58 UTC, jypthemiracle commented on BE/src/main/resources/application-oauth.yml
> +  clientId : bdd909bfff2137535182
@guswns1659 제 생각에는 profiles 설정이 안된 것 같은데요. 정확히는 dev profile 사용을 가리키는데 oauth 설정을 가리키지 않아서 그런 것 같네요.
다음과 같이 바꿔주세요. (google 예시)
```yml
spring:
  profiles: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 클라이언트 아이디
            client-secret: 클라이언트 시크릿
            scope: profile, email
```

참고로 깃헙도 있어요.
* https://github.com/wonwoo/spring-boot-oauth2-login

2020-06-15 03:13 UTC, jypthemiracle commented on BE/src/main/resources/application-oauth.yml
> +  clientId : bdd909bfff2137535182
아니면 이렇게요. 별도로 분리하고 싶으면 real 프로파일이랑 같이 지정해줘야 합니다.

```
spring:
  profiles:
    active: dev
	include: oauth
```

* https://tramyu.github.io/java/spring/spring-profile/

2020-06-15 03:25 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +	public ResponseEntity<Void> login(String code, HttpServletResponse response) {
기존 프로젝트에서 리턴값을 없이 HTTP 헤더값으로 구분을 했던터라 그대로 사용했는데 바꿔도 됩니당.

2020-06-15 03:26 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/utils/GithubProperties.java
> +@ConfigurationProperties("github")
프로퍼티를 객체로 관리할 때 사용하면 좋아요!

2020-06-15 03:42 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/service/LoginService.java
> +		if (userId.contains("\"")) {
깃허브에 accessToken으로 유저이메일을 요청하면 "가 붙어서 와요. 그래서 그거 제거하는 코드에요! 아래 사진 참고하면 "가 하나 붙어서 와요

![image](https://user-images.githubusercontent.com/55608425/84616006-889e6280-af05-11ea-8090-5cfdd0a0bb4e.png)

2020-06-15 08:29 UTC, jypthemiracle commented
@guswns1659 논의해보아야 할 사항.
* ```SessionUser```를 사용할 필요가 없으니 리팩토링. 쿠키를 사용합시다.
* ```JWT``` 토큰을 활용하여 인증할 수 있도록 기능을 추가합시다.

2020-06-15 08:30 UTC, sigridjineth approved these changes
대체로 잘 구현하셨네요.
스프링 시큐리티는 원리를 모르고 사용했으면 확실히 어려운 주제였을 것 같습니다.

@guswns1659 추가로 작업해야 할 사항은 다음과 같네요.

1. SessionUser를 사용할 필요가 없으니 리팩토링. 쿠키를 사용합시다.
2. JWT 토큰을 활용하여 인증할 수 있도록 기능을 추가합시다.

2020-06-15 08:30 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/config/RestTemplateConfig.java
> +			.setConnectTimeout(Duration.ofMillis(5000))
현재 이 부분에서 컴파일 오류가 나고 있습니다.
Duration을 Int로 변환하지 못한다고 하네요.

2020-06-15 08:31 UTC, merged