[BE] feat : 필터별 검색을 위한 최종 API
codesquad-member-2020/issue-tracker-04 pull request #94
Opened 2020-06-23 12:04 UTC by guswns1659

- FilterParamRequestDto 생성, 필터 검색 때 전달받는 Dto
- IssueController.filtering() 생성.
- IssueService.filtering() 생성.

2020-06-23 15:03 UTC, sigridjineth requested changes
수고하셨고, 제 의견을 많이 남겨드렸습니다. 하나의 의견이라고만 생각해주시구요.
일단 테스트를 통과하지 않아 Request Changes 남겨드렸습니다.
몇 가지 도전 질문을 남겨드렸는데요. Jack의 대댓글을 기다릴게요.
토론할 거리 있으시면 언제든지 Slack 메시지 주시구요. 내일 코쿼에서 뵙겠습니다.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
> +			.anyMatch(assignee -> assignee.getGithubId().equals(userId));
이전에 공유드렸던 디미터 법칙에 대한 글을 기억하시나요?
현재 코드는 assignee의 깃헙 아이디를 꺼내서 비교하고 있습니다.
보통 점(.)이 찍혀있다는 것은 객체 간의 결합도가 있다는 뜻인데요. 현재 2군데나 찍혀있네요. 코드 스멜이 느껴지는 부분입니다.
assignee라는 별도의 객체의 책임과 역할을 존중하지 않는 셈인데요.
assignee에게 신호를 보내서 userId와 자신의 아이디를 자율적으로 비교하도록 리팩토링하면 어떨까요?

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
> +		return this.comments.hasUserId(userId);
객체에게 직접 신호를 보내고 있는 코드입니다. 아주 좋아요 👍

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/IssueRepository.java
> +    List<Issue> findIssuesByStatus(Status status);
Optional로 주면 어떨까요? Null일 수 있으니까요. 한 번 Wrap하는 것도 좋겠습니다.
저는 옵셔널을 매우 좋아하는데요. 혹자는 옵셔널이 비싸기 때문에 조심해서 사용해야 한다는 입장인데요. 저도 이에 동의하는 입장이나, 개인적인 생각에 컴퓨팅 자원이 충분한 현대에는 옵셔널에 대한 사용을 굳이 자제할 필요는 없다고 생각합니다. AWS 서버 늘리는 것이 개발자를 더욱 고용해야 하는 비용이나 NPE로 인하여 잃을 수 있는 비즈니스 비용이 더 크다고 생각합니다. 혹시나 옵셔널 사용을 주저하실까봐 노파심에 적어봅니다.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Comments.java
> +			return new Comment();
우리 지금 ```Comment.NullCommentOf()```가 있을 겁니다. 해당 Null Object 생성자를 사용해주시면 어떨까요?

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Comments.java
> +			.anyMatch(comment -> comment.getUser().getGithubId().equals(userId));
여기도 위의 댓글에서 말한 것과 같은 맥락에서 리팩토링 대상이라고 생각합니다.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Labels.java
> +			.anyMatch(label -> label.getTitle().equals(labelName));
여기도 디미터 법칙 위반이네요. 다시한번 재고해주세요.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
> +	void 필터된_이슈를_가져온다(String status, String role, String option, String value, String expected) {
이번 PR 제가 Pull해서 받았는데 테스트를 통과하지 못하네요.
스키마 작성을 필터링해야 하는데, SQL 작성이 담긴 이슈가 반환됩니다.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		if (!role.equals("null")) {
현재 if-else if로 점철되어 있는데요.
개인적으로는 이렇게 할 수밖에 없을 때에는 차라리 switch 문을 선호하는 편입니다. 물론 많은 사람들이 switch 문의 사용도 그리 권하고 있지는 않아요.
이럴 때에는 메소드를 분리하는 것이 맞다고 생각합니다. 현재 role에 따라서 필터링 조건이 분기되고 있는데요. 조건을 분기해야 하는 role의 수만큼 메소드를 나눠보세요.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		RealUser user = userRepository.findByGithubId(userId).orElseGet(NullUser::of);
**도전 질문**

Jack이 생각하시기에,
A. Service는 자신이 담당하지 않는 객체에 접근해야 할 때, 자신의 객체에 해당하지 않는 Service를 참조하는 것이 맞다고 생각하시나요?
B. 자신의 객체에 해당하지 않는 Repository를 참조하는 것이 맞다고 생각하시나요? 

다시 말해서 RealUser를 가져올 때 userService를 참조하는 것이 맞다고 생각하시나요? 아니면 userRepository로 직접 접근하는 것이 맞다고 생각하시나요?

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +				issuesByFiltering = issueRepository.findIssuesByStatusAndUserGithubId(status, userId);
현재 issueRepository에서 직접 Status와 UserGitHubId로 찾아오도록 구현하셨습니다.

**도전 질문**
가. Repository 단에서 조건에 따라 필터링하여 가져온다. Service는 Repository의 반환 결과를 가공 없이 이용한다.
나. Repository 단에서는 가공 없이 모든 객체를 가져온다. Service는 Repository가 가져온 모든 결과를 가공하여 조건에 맞게 이용한다.

어떤 선택이 더 합리적이라고 생각하시나요? 그 이유는 무엇인가요?

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +			} else {
**도전 질문**
else 문 사용을 피하라는 말을 주로 들어보셨을 텐데요. 그 이유가 혹시 무엇이라고 생각하시나요?

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +				issuesByFiltering = issuesByFiltering.stream()
스트림의 사용은 비쌉니다. 앞서 옵셔널과 마찬가지로 람다와 스트림의 메모리 점유는 상당한 편인데요. 저는 컴퓨팅 자원의 비용이 점점 저렴해지고 있는 만큼 스트림 사용을 주저할 필요가 없다고 생각합니다. 다만 너무 남발하는 것은 좋지 않으니 하나의 메소드에 너무 많은 스트림을 구현한 것은 아닌가 재고해주시구요.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +					.filter(issue -> issue.getUser().getGithubId().equals(value))
여기도 디미터 법칙을 위반하고 있지요. 객체가 자율적으로 조건을 선별하여 결과를 리턴하도록 리팩토링해보세요.

2020-06-23 15:03 UTC, realsigridjin commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		return IssueOverviewResponseDtos.builder()
한 메소드가 DTO 생성과 필터링이라는 두 가지 책임을 모두 맡고 있네요.
메소드 하나가 하나의 책임만 기능하도록 리팩토링 해보세요.

2020-06-23 15:03 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +	private List<Issue> findIssuesByStatusAndCommentsByUser(List<Issue> issuesByFiltering, String userId) {
메소드가 한 가지 책임만 맡고 있으며, 조건에 따른 필터링을 이행하고자 스트림을 적절히 활용하셨네요. 👍

2020-06-23 15:03 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
> +	public IssueOverviewResponseDtos filtering(@RequestParam String status, @RequestParam(required = false, defaultValue = "null") String role,
```defaultValue```가 null인 것보다 더 좋은 네이밍이 없을까요. 예를 들어 `all`이 어떨까요. 혹자가 보면 String의 null이지만, 객체가 없는 null 타입으로 오해할 수도 있습니다.

2020-06-23 15:03 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
> +																@RequestParam(required = false, defaultValue = "null") String value,
현재 ```@RequestParam```의 다양한 옵션을 활용하여 적절히 기능을 구현해주셨네요. 좋습니다.

2020-06-23 15:03 UTC, jypthemiracle commented on BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
> +		String url = "http://localhost:" + port + "/api/v1/filter?status=open&option=author&value=guswns1659";
확장성이 있는 테스트를 만들기 위해 option이나 value는 별도의 상수로 분리하면 어떨까 싶은데 한 번 고려해주세요.

2020-06-23 15:03 UTC, jypthemiracle commented on BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
> +		IssueOverviewResponseDtos issueOverviewResponseDtos = webTestClient
꾸준한 컨트롤러 테스트가 아주 좋습니다.

2020-06-24 03:27 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		RealUser user = userRepository.findByGithubId(userId).orElseGet(NullUser::of);
@jypthemiracle 
저는 A라 적절한 접근 방식이라 생각해요! 담당하지 않는 다른 객체를 바로 접근하는 것보단 서비스에게 메세지를 보내는 방식이 낫다고 봅니다! 이런 맥락에서 위 로직은 리팩토링이 필요할 거 같네요!

2020-06-24 03:31 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +				issuesByFiltering = issueRepository.findIssuesByStatusAndUserGithubId(status, userId);
@jypthemiracle 
저는 (가)가 합리적이라 생각하네요. repository에서 적절한 퀴리문을 사용해서 필요한 객체를 추출하는 게 repository를 적절히 사용하는 방법같아요. 성능도 더 나을 것 같네요.

2020-06-24 03:32 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +			} else {
@jypthemiracle 
예상치 못한 예외도 else문에 속하기 때문에 문제가 발생할 것 같네요!? 그래서 else문을 지양하는 걸 추천하는 것 같네요

2020-06-24 03:39 UTC, guswns1659 commented on BE/src/test/java/com/codesquad/issue04/service/IssueServiceTest.java
> +	void 필터된_이슈를_가져온다(String status, String role, String option, String value, String expected) {
테스트 케이스 중 expected에 "스키마 작성"이 아니라 "SQL 작성"이어야 하네요. 테스트 케이스를 잘못 입력했어요!

2020-06-24 04:22 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		RealUser user = userRepository.findByGithubId(userId).orElseGet(NullUser::of);
@guswns1659 
저의 생각은 이렇습니다. 이렇게 A 객체와 B 객체를 모두 다뤄야 하는 A 서비스가 있다면, 해당 서비스의 이름을 바꾸어야 한다고 생각합니다. A와 B를 모두 포괄적으로 표현할 수 있는 이름으로요.
같은 레이어의 서비스 클래스들이 서로를 참조하는 것보다, 차라리 Repository 레벨로 서로를 참조하는 것이 훨씬 더 좋은 방향이라고 생각됩니다. 일단, circular reference 문제를 막을 수도 있습니다. A 서비스가 B 서비스를 참조하는데, B 서비스가 A 서비스를 참조하면 Bean 생성 시에 순환 참조 오류를 겪기 때문입니다. (다른 해결 방식이 있기는 한데 너무 복잡해서 패스합시다.)

2020-06-24 04:24 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +		RealUser user = userRepository.findByGithubId(userId).orElseGet(NullUser::of);
따라서 유지보수의 측면에서 Repository를 직접 참조하는 것이 좋겠다는 의견입니다.

2020-06-24 04:26 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +				issuesByFiltering = issueRepository.findIssuesByStatusAndUserGithubId(status, userId);
@guswns1659 
저는 (나)의 방식을 지지하는 입장입니다. 왜냐하면, 하나의 쿼리 메소드만 사용하기에 유지보수 비용이 줄어들고 조금 더 객체지향스럽게 코딩할 수 있습니다.
JPA를 사용하는 이유는 쿼리문 작성을 최대한 자제하고, 절차지향적인 사고를 최대한 피하고자 하는 의도인데요. 객체지향의 관점에서 바라보면 하나의 객체가 자신이 필요로 하는 원소를 자율적으로 추출하여 사용하는 것이 훨씬 유지보수하기 쉽다고 생각됩니다.
물론 Jack 말대로 직접 쿼리 메소드를 만드는 것이 성능 문제에 있어서 훨씬 유리할 수 있습니다. 하지만 우리 입장에서는 성능이 큰 이슈가 아니고, 얼마나 설계를 유지보수하기 좋은 구조로 만드느냐에 방점이 찍혀있는 것 같습니다.

2020-06-24 04:29 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/service/IssueService.java
> +			} else {
@guswns1659 
저는 조건이 복잡해지기 때문에 사용을 지양해야 하는 것이 아닌가 생각하고 있습니다.
else에 수반하는 조건은 상당히 모호하기 때문에(if문의 여집합) 사이드 이펙트가 어떻게 발생할 지 알 수 없습니다.
바로 return을 시키고 새로운 조건을 메소드화하여 캡슐화된 상태로 if문을 새로 작성하면 조건 분기도 유지보수하기 용이합니다.

2020-06-24 04:30 UTC, jypthemiracle commented
@guswns1659 
대댓글 감사합니다. 저의 생각을 몇 개 달아두었으니 참고하시고 토론 거리가 있으면 알려주세요.
리팩토링 완료하시면 디엠 주시구요. 다시 코드리뷰하여 검토드리도록 하겠습니다.

2020-06-24 04:30 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/domain/issue/vo/firstcollection/Comments.java
> +			return new Comment();
@jypthemiracle 
Comment엔 없어서 Comment.ofNullComment()만들었어요!

2020-06-24 04:33 UTC, guswns1659 commented on BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
> +	public IssueOverviewResponseDtos filtering(@RequestParam String status, @RequestParam(required = false, defaultValue = "null") String role,
@jypthemiracle 
empty로 변경했습니다!

2020-06-24 04:37 UTC, guswns1659 commented on BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
> +		String url = "http://localhost:" + port + "/api/v1/filter?status=open&option=author&value=guswns1659";
좋네요! 별도의 상수로 뺐습니다!

2020-06-24 10:18 UTC, sigridjineth approved these changes
수고 많으셨습니다.
피드백 반영이 잘 된 것 같습니다. 머지할게요.

2020-06-24 10:18 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/utils/Filter.java
> +public enum Filter {
enum 사용 좋네요 👍

2020-06-24 10:18 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/domain/issue/Issue.java
> +			.anyMatch(assignee -> assignee.isSameUser(userId));
리팩토링 잘 하셨습니다. 👍

2020-06-24 10:18 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
> +	@GetMapping("/v1/issues")
머지시킨 다음에 ```v1```은 제하도록 합시다.

2020-06-24 10:18 UTC, jypthemiracle commented on BE/src/main/java/com/codesquad/issue04/web/controller/IssueController.java
> +		return issueService.responseFiltering(filterParamRequestDto);
역할과 책임을 잘 분리하셨어요. 👍

2020-06-24 10:18 UTC, jypthemiracle commented on BE/src/test/java/com/codesquad/issue04/web/controller/IssueControllerTest.java
> +			.responseTimeout(Duration.ofMillis(30000))
타임아웃 설정을 ```@BeforeEach```에서 할 수 있군요.

2020-06-24 10:18 UTC, merged